# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA/RISC-V/AX7010_2023.1-course_s1_fpga-18_ad9238_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/dpram2048x8/dpram2048x8.xci
# IP: The module: 'dpram2048x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/RISC-V/AX7010_2023.1-course_s1_fpga-18_ad9238_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/dpram2048x8/dpram2048x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram2048x8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/FPGA/RISC-V/AX7010_2023.1-course_s1_fpga-18_ad9238_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/dpram2048x8/dpram2048x8.xci
# IP: The module: 'dpram2048x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/RISC-V/AX7010_2023.1-course_s1_fpga-18_ad9238_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/dpram2048x8/dpram2048x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram2048x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
