############## clock and reset define##################
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN U18 [get_ports sys_clk]

set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN N15 [get_ports rst_n]
############## HDMI_O###########################
set_property IOSTANDARD TMDS_33 [get_ports TMDS_clk_n]
set_property PACKAGE_PIN N18 [get_ports TMDS_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports TMDS_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[0]}]
set_property PACKAGE_PIN V20 [get_ports {TMDS_data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[1]}]
set_property PACKAGE_PIN T20 [get_ports {TMDS_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[2]}]
set_property PACKAGE_PIN N20 [get_ports {TMDS_data_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[2]}]
set_property PACKAGE_PIN V16 [get_ports {hdmi_oen[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_oen[0]}]

##############AX7020 and AX7010  J11##################
# set_property PACKAGE_PIN F17 [get_ports ad9238_clk_ch1]
# set_property PACKAGE_PIN F16 [get_ports {ad9238_data_ch1[0]}]
# set_property PACKAGE_PIN F20 [get_ports {ad9238_data_ch1[1]}]
# set_property PACKAGE_PIN F19 [get_ports {ad9238_data_ch1[2]}]
# set_property PACKAGE_PIN G20 [get_ports {ad9238_data_ch1[3]}]
# set_property PACKAGE_PIN G19 [get_ports {ad9238_data_ch1[4]}]
# set_property PACKAGE_PIN H18 [get_ports {ad9238_data_ch1[5]}]
# set_property PACKAGE_PIN J18 [get_ports {ad9238_data_ch1[6]}]
# set_property PACKAGE_PIN L20 [get_ports {ad9238_data_ch1[7]}]
# set_property PACKAGE_PIN L19 [get_ports {ad9238_data_ch1[8]}]
# set_property PACKAGE_PIN M20 [get_ports {ad9238_data_ch1[9]}]
# set_property PACKAGE_PIN M19 [get_ports {ad9238_data_ch1[10]}]
# set_property PACKAGE_PIN K18 [get_ports {ad9238_data_ch1[11]}]


set_property PACKAGE_PIN H17 [get_ports ad9238_clk_ch0]
set_property PACKAGE_PIN H20 [get_ports {ad9238_data_ch0[0]}]
set_property PACKAGE_PIN L17 [get_ports {ad9238_data_ch0[2]}]
set_property PACKAGE_PIN M18 [get_ports {ad9238_data_ch0[4]}]
set_property PACKAGE_PIN D20 [get_ports {ad9238_data_ch0[6]}]
set_property PACKAGE_PIN E19 [get_ports {ad9238_data_ch0[8]}]
set_property PACKAGE_PIN G18 [get_ports {ad9238_data_ch0[10]}]



set_property IOSTANDARD LVCMOS33 [get_ports ad9238_clk_ch0]
set_property IOSTANDARD LVCMOS33 [get_ports {ad9238_data_ch0[*]}]
# set_property IOSTANDARD LVCMOS33 [get_ports ad9238_clk_ch1]
# set_property IOSTANDARD LVCMOS33 [get_ports {ad9238_data_ch1[*]}]

# set_property IOB TRUE [get_ports {ad9238_data_ch1[*]}]
set_property IOB TRUE [get_ports {ad9238_data_ch0[*]}]

# set_property PACKAGE_PIN H16 [get_ports SCLK]
# set_property PACKAGE_PIN G15 [get_ports MOSI]
# set_property PACKAGE_PIN H15 [get_ports MISO]
# set_property PACKAGE_PIN J14 [get_ports DRDY]
# set_property PACKAGE_PIN K14 [get_ports CS]
# set_property IOSTANDARD LVCMOS33 [get_ports MOSI]
# set_property IOSTANDARD LVCMOS33 [get_ports SCLK]
# set_property IOSTANDARD LVCMOS33 [get_ports CS]
# set_property IOSTANDARD LVCMOS33 [get_ports MISO]
# set_property IOSTANDARD LVCMOS33 [get_ports DRDY]

# set_property PACKAGE_PIN W19 [get_ports ALI]
# set_property PACKAGE_PIN W18 [get_ports BLI]
# set_property IOSTANDARD LVCMOS33 [get_ports BLI]
# set_property IOSTANDARD LVCMOS33 [get_ports ALI]



set_property PACKAGE_PIN F20 [get_ports CLI]
set_property PACKAGE_PIN F19 [get_ports DLI]
set_property IOSTANDARD LVCMOS33 [get_ports CLI]
set_property IOSTANDARD LVCMOS33 [get_ports DLI]

# set_property PACKAGE_PIN R17 [get_ports key_flag]
# set_property IOSTANDARD LVCMOS33 [get_ports key_flag]

set_property PACKAGE_PIN F17 [get_ports square_wave]
set_property IOSTANDARD LVCMOS33 [get_ports square_wave]


# set_property PACKAGE_PIN F16 [get_ports Photogate_judge]
# set_property IOSTANDARD LVCMOS33 [get_ports Photogate_judge]

set_property PACKAGE_PIN J20 [get_ports {ad9238_data_ch0[1]}]
set_property PACKAGE_PIN L16 [get_ports {ad9238_data_ch0[3]}]
set_property PACKAGE_PIN M17 [get_ports {ad9238_data_ch0[5]}]
set_property PACKAGE_PIN D19 [get_ports {ad9238_data_ch0[7]}]
set_property PACKAGE_PIN E18 [get_ports {ad9238_data_ch0[9]}]
set_property PACKAGE_PIN G17 [get_ports {ad9238_data_ch0[11]}]

set_property PACKAGE_PIN M14 [get_ports over]
set_property PACKAGE_PIN M15 [get_ports succ]
set_property PACKAGE_PIN G20 [get_ports uart_rx_pin]
set_property PACKAGE_PIN G19 [get_ports uart_tx_pin]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_pin]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx_pin]
# set_property IOSTANDARD LVCMOS33 [get_ports spi_miso]
# set_property IOSTANDARD LVCMOS33 [get_ports spi_mosi]
# set_property IOSTANDARD LVCMOS33 [get_ports spi_clk]
# set_property IOSTANDARD LVCMOS33 [get_ports spi_ss]
set_property IOSTANDARD LVCMOS33 [get_ports over]
set_property IOSTANDARD LVCMOS33 [get_ports succ]
# set_property PACKAGE_PIN H16 [get_ports spi_clk]
# set_property PACKAGE_PIN G15 [get_ports spi_mosi]
# set_property PACKAGE_PIN H15 [get_ports spi_miso]
# set_property PACKAGE_PIN K14 [get_ports spi_ss]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clk_IBUF]

set_property PACKAGE_PIN N16 [get_ports uart_debug_pin]
set_property IOSTANDARD LVCMOS33 [get_ports uart_debug_pin]

set_property PACKAGE_PIN H16 [get_ports {gpio[0]}]
set_property PACKAGE_PIN G15 [get_ports {gpio[1]}]
set_property PACKAGE_PIN H15 [get_ports {gpio[2]}]
set_property PACKAGE_PIN J14 [get_ports {gpio[3]}]
set_property PACKAGE_PIN K14 [get_ports {gpio[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[3]}]

set_property PACKAGE_PIN W19 [get_ports {gpio[5]}]
set_property PACKAGE_PIN W18 [get_ports {gpio[6]}]
set_property PACKAGE_PIN R14 [get_ports {gpio[7]}]
set_property PACKAGE_PIN P14 [get_ports {gpio[8]}]
set_property PACKAGE_PIN Y17 [get_ports {gpio[9]}]
set_property PACKAGE_PIN Y16 [get_ports {gpio[10]}]
set_property PACKAGE_PIN W15 [get_ports {gpio[11]}]
set_property PACKAGE_PIN V15 [get_ports {gpio[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[5]}]
