# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/FPGA/RISC-V/AX7010_2023.1-course_s1_fpga-18_ad9238_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/adc_pll/adc_pll.xci
# IP: The module: 'adc_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/RISC-V/AX7010_2023.1-course_s1_fpga-18_ad9238_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/adc_pll/adc_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FPGA/RISC-V/AX7010_2023.1-course_s1_fpga-18_ad9238_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/adc_pll/adc_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FPGA/RISC-V/AX7010_2023.1-course_s1_fpga-18_ad9238_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/adc_pll/adc_pll_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FPGA/RISC-V/AX7010_2023.1-course_s1_fpga-18_ad9238_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/adc_pll/adc_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/FPGA/RISC-V/AX7010_2023.1-course_s1_fpga-18_ad9238_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/adc_pll/adc_pll.xci
# IP: The module: 'adc_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/RISC-V/AX7010_2023.1-course_s1_fpga-18_ad9238_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/adc_pll/adc_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FPGA/RISC-V/AX7010_2023.1-course_s1_fpga-18_ad9238_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/adc_pll/adc_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FPGA/RISC-V/AX7010_2023.1-course_s1_fpga-18_ad9238_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/adc_pll/adc_pll_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FPGA/RISC-V/AX7010_2023.1-course_s1_fpga-18_ad9238_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/adc_pll/adc_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
