# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/rom_tri/rom_tri.xci
# IP: The module: 'rom_tri' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/rom_tri/rom_tri_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_tri'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/rom_tri/rom_tri.xci
# IP: The module: 'rom_tri' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/rom_tri/rom_tri_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_tri'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
