# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/ad_hdmi/vivado_ad9238/vivado_ad9238.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/ad_hdmi/vivado_ad9238/vivado_ad9238.cache/wt [current_project]
set_property parent.project_path E:/ad_hdmi/vivado_ad9238/vivado_ad9238.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/ad_hdmi/auto_create_project/my_ip [current_project]
update_ip_catalog
set_property ip_output_repo e:/ad_hdmi/vivado_ad9238/vivado_ad9238.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files E:/ad_hdmi/vivado_ad9238/tool/triwave.coe
add_files E:/ad_hdmi/vivado_ad9238/tool/sinwave.coe
read_verilog -library xil_defaultlib {
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/ADC_CLK_Div.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/SPWM_Time.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/ad9238_sample.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/core/defines.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/core/clint.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/video_define.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/color_bar.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/core/csr_reg.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/core/ctrl.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/core/div.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/core/ex.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/utils/gen_dff.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/perips/gpio.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/grid_display.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/core/id.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/core/id_ex.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/core/if_id.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/core/pc_reg.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/perips/ram.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/core/regs.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/core/rib.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/perips/rom.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/perips/timer.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/timing_gen_xy.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/core/tinyriscv.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/soc/tinyriscv_soc_top.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/perips/uart.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/rtl/debug/uart_debug.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/wav_display.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/wave.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/wave_clk.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/wave_comparator.v
  E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/new/top.v
}
read_ip -quiet E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc]

read_ip -quiet E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/video_pll/video_pll.xci
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/video_pll/video_pll_board.xdc]
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/video_pll/video_pll.xdc]
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/video_pll/video_pll_ooc.xdc]

read_ip -quiet E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/rom_sin/rom_sin.xci
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/rom_sin/rom_sin_ooc.xdc]

read_ip -quiet E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

read_ip -quiet E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/dpram2048x8/dpram2048x8.xci
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/dpram2048x8/dpram2048x8_ooc.xdc]

read_ip -quiet E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/adc_pll/adc_pll.xci
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/adc_pll/adc_pll_board.xdc]
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/adc_pll/adc_pll.xdc]
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/adc_pll/adc_pll_late.xdc]
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/adc_pll/adc_pll_ooc.xdc]

read_ip -quiet E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/rom_tri/rom_tri.xci
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/rom_tri/rom_tri_ooc.xdc]

read_ip -quiet E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/ila_0_1/ila_0.xci
set_property used_in_synthesis false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/sources_1/ip/ila_0_1/ila_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/constrs_1/new/ad9238_hdmi.xdc
set_property used_in_implementation false [get_files E:/ad_hdmi/vivado_ad9238/vivado_ad9238.srcs/constrs_1/new/ad9238_hdmi.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7z010clg400-1
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
